name=ESP32FTPServer
version=0.0.6
author=Annabel369
maintainer=Annabel369
sentence=Simple FTP Server on SD Card for Espressif ESP32
paragraph=Otimizado para arquivos grandes (MP4, ZIP) e navegação estável em subpastas no Windows e FileZilla.
category=Communication
url=https://github.com/Annabel369/ESP32FTPServer
architectures=esp32
includes=ESP32FtpServer.h