name=ESP32FtpServer
version=1.0.3
author=Annabel369
maintainer=Annabel369 <amauri00007@gmail.com>
sentence=Simple FTP Server on SD Card for Espressif ESP32.
paragraph=Otimizado para arquivos grandes (MP4, ZIP) e navegação estável em subpastas no Windows e FileZilla.
category=Communication
url=github.com
architectures=esp32
includes=ESP32FtpServer.h
